//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSharp.Generated.NativeClasses {
    using System.ComponentModel;
    using System.Runtime.InteropServices;
    using System;
    
    
    public interface IAppSystem {
        
        /// <param name='factory'></param>
        bool Connect(System.IntPtr factory);
        
        void Disconnect();
        
        /// <param name='pInterfaceName'></param>
        System.IntPtr QueryInterface(string pInterfaceName);
        
        System.IntPtr Init();
        
        void Shutdown();
    }
}
