//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSharp.Generated.NativeClasses {
    using System.ComponentModel;
    using System.Runtime.InteropServices;
    using System;
    
    
    public interface ILuaShared {
        
        void dtorILuaShared();
        
        /// <param name='param0'></param>
        /// <param name='param1'></param>
        /// <param name='param2'></param>
        /// <param name='param3'></param>
        void Init(System.IntPtr param0, bool param1, System.IntPtr param2, System.IntPtr param3);
        
        void Shutdown();
        
        void DumpStats();
        
        /// <param name='param0'></param>
        /// <param name='param1'></param>
        System.IntPtr CreateLuaInterface(byte param0, bool param1);
        
        /// <param name='param0'></param>
        void CloseLuaInterface(System.IntPtr param0);
        
        /// <param name='param0'></param>
        System.IntPtr GetLuaInterface(byte param0);
        
        /// <param name='param0'></param>
        /// <param name='param1'></param>
        /// <param name='param2'></param>
        /// <param name='param3'></param>
        void LoadFile(System.IntPtr param0, System.IntPtr param1, bool param2, bool param3);
        
        /// <param name='param0'></param>
        void GetCache(System.IntPtr param0);
        
        /// <param name='param0'></param>
        void MountLua(string param0);
        
        /// <param name='param0'></param>
        /// <param name='param1'></param>
        void MountLuaAdd(string param0, string param1);
        
        /// <param name='param0'></param>
        void UnMountLua(string param0);
        
        /// <param name='param0'></param>
        /// <param name='param1'></param>
        void SetFileContents(string param0, string param1);
        
        /// <param name='param0'></param>
        void SetLuaFindHook(System.IntPtr param0);
        
        /// <param name='param0'></param>
        /// <param name='param1'></param>
        /// <param name='param2'></param>
        void FindScripts(System.IntPtr param0, System.IntPtr param1, int param2);
    }
}
